name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: ls
      run: ls /usr/local/share/boost/1.69.0/lib
    - name: ls
      run: ls /usr/local/share/boost/1.69.0/libs
    - name: Interval Test
      run: |
        g++ -std=c++17 -I/usr/local/share/boost/1.69.0/include -L/usr/local/share/boost/1.69.0/lib -I./include -lboost_unit_test_framework-mt-x64 tests/interval.cpp -o interval
        ./interval
    - name: Lexer Test
      run: |
        g++ -std=c++17 -I/usr/local/share/boost/1.69.0/include -L/usr/local/share/boost/1.69.0/lib -I/usr/local/include -I./include -lboost_unit_test_framework tests/lexer.cpp -o lexer
        ./lexer
    - name: Parser Test
      run: |
        g++ -std=c++17 -I/usr/local/share/boost/1.69.0/include -L/usr/local/share/boost/1.69.0/lib -I/usr/local/include -I./include -lboost_unit_test_framework tests/parser.cpp -o parser
        ./parser
    - name: Token Test
      run: |
        g++ -std=c++17 -I/usr/local/share/boost/1.69.0/include -L/usr/local/share/boost/1.69.0/lib -I/usr/local/include -I./include -lboost_unit_test_framework tests/token.cpp -o token
        ./token
    - name: Version Test
      run: |
        g++ -std=c++17 -I/usr/local/share/boost/1.69.0/include -L/usr/local/share/boost/1.69.0/lib -I/usr/local/include -I./include -lboost_unit_test_framework tests/version.cpp -o version
        ./version
